### ISSUE TITLE
Trouble with installation

### ISSUE THREAD

**Issue by up201806330** [JimmyCushnie/FancyTextRendering#14]
I'm still having trouble getting your tool up and running. You mentioned that I may need to reference the **FancyTextRendering** assembly in my code, but according to the [documentation](https://docs.unity3d.com/Manual/ScriptCompilationAssemblyDefinitionFiles.html) this is done automatically for all assemblies inside the Assets folder, right?

![image](https://user-images.githubusercontent.com/45789887/109716279-93387f00-7b9c-11eb-8a17-75e53ca3f1cc.png)

With this I'm assuming the other dependencies you mentioned are installed correctly, but I don't understand why this assembly file isn't being recognized.

**Comment by JimmyCushnie** [comment]
A few things to test:

- Are there any compiler errors?
- Can you add the FTR monobehaviors to gameobjects?
- Are you able to reference the scripts if you put *your* code inside an asmdef, and give it an explicit reference to FTR?

I'm not really sure how auto-referenced asmdefs work, I always use explicit references.

**Comment by up201806330** [comment]
(I appreciate the lightning fast reply <3)

1st
![image](https://user-images.githubusercontent.com/45789887/109717103-8cf6d280-7b9d-11eb-9f6b-edb3cc9cf90e.png)

2nd
Yes! And they work like a charm
![image](https://user-images.githubusercontent.com/45789887/109717243-b31c7280-7b9d-11eb-91ad-cc41de0d4ef7.png)

3rd
Never really used asmdef's, kind of shooting in the dark here
Created this assembly definition in the folder with my script, and added a dependency to FTR. Still no luck
![image](https://user-images.githubusercontent.com/45789887/109717962-a1879a80-7b9e-11eb-8b23-677944b8ec03.png)
![image](https://user-images.githubusercontent.com/45789887/109718109-cf6cdf00-7b9e-11eb-9dd7-811305c3c7cf.png)

**Comment by JimmyCushnie** [comment]
Does `ProjectGetter` have `using FancyTextRendering;` at the top of the file?

**Comment by up201806330** [comment]
I removed it before creating the asmdef and upon adding it again, it now doesn't even recognize the assembly (it didnt give this error before creating APIStuff)

![image](https://user-images.githubusercontent.com/45789887/109719150-23c48e80-7ba0-11eb-8a80-2905e86051f1.png)
![image](https://user-images.githubusercontent.com/45789887/109719175-2f17ba00-7ba0-11eb-994d-a2a1a4f84ac8.png)

**Comment by JimmyCushnie** [comment]
What the hell. I am so confused.

If you clone the entire FTR project does it work properly? If so, you might be able to figure out the problem by checking the differences between the FTR project and your new project with FTR added.

**Comment by JimmyCushnie** [comment]
Oh, you might also try the following:

1. Close the Unity editor
2. Delete your project's `Library` folder (this is a Unity cache)
3. Re-open the project in Unity. (It will re-generate the `Library` folder)

Sometimes Unity does a widdle fucko boingo when compiling scripts. This resets all its cached information and can fix weird errors.

**Comment by up201806330** [comment]
Throughout this whole process I've been hitting Reimport all after almost every change. There doesn't seem to be a library folder in my project *shrug*. I'm reading online about vscode having trouble with assemblies, Im going to investigate that a little further and then will clone your demo project

**Comment by JimmyCushnie** [comment]
There... doesn't seem to be a library folder? If you're correct about that, Unity shouldn't be working at all. This is what a project folder is supposed to look like:

![image](https://user-images.githubusercontent.com/32693298/109720665-5fe3f900-7b78-11eb-8fce-a27747e6c87f.png)

I have occasionally encountered issues that "reimport all" does not fix, but deleting the `Library` folder does.

**Comment by up201806330** [comment]
Ok I wrongly assumed it could be seen from the explorer in the Unity editor. I deleted it and still no luck. Im going to clone your project now

**Comment by up201806330** [comment]
Taking a look at your code I saw you used **using LogicUI.FancyTextRendering;**
After reimporting, the editor shows no more errors!

**Comment by JimmyCushnie** [comment]
Aaaaah, yes, that's the problem! My apologies -- I originally considered changing all the namespaces from `LogicUI.FancyTextRendering` to just `FancyTextRendering`, but I eventually decided not to in order to make cross-development easier between this repo and my main LogicUI repo, as well as to enable forward compatibility for FTR projects when I release LogicUI. I forgot that I'd decided not to do it when talking with you however.

I'm glad you've got it working! Best of luck with your project :D
